version: '2'
services:
    bankingapi-app:
        image: bankingapi
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://bankingapi-postgresql:5432/BankingAPI
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    bankingapi-postgresql:
        extends:
            file: postgresql.yml
            service: bankingapi-postgresql
